version: '3.8'

services:
  # FastAPI server
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - COPERNICUS_USER=${COPERNICUS_USER}
      - COPERNICUS_PASS=${COPERNICUS_PASS}
      - ADMIN_API_KEY=${ADMIN_API_KEY:-abfi-admin-2024}
      - GCS_BUCKET=${GCS_BUCKET}
      - NOTIFICATION_WEBHOOK=${NOTIFICATION_WEBHOOK}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Scheduler for daily polygon generation
  scheduler:
    build: .
    command: python scheduler.py
    environment:
      - COPERNICUS_USER=${COPERNICUS_USER}
      - COPERNICUS_PASS=${COPERNICUS_PASS}
      - RUN_ON_STARTUP=${RUN_ON_STARTUP:-false}
      - GCS_BUCKET=${GCS_BUCKET}
      - NOTIFICATION_WEBHOOK=${NOTIFICATION_WEBHOOK}
      - POLYGONS_BACKEND_URL=http://api:8000
    volumes:
      - ./data:/app/data
    depends_on:
      - api
    restart: unless-stopped

volumes:
  data:
